spring:
  datasource:
    url: jdbc:postgresql://db:5432/cloud_storage_docker_container
    #url: jdbc:postgresql://localhost:5432/cloud_storage
    username: postgres
    password: N8x#qLz92!rT
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  upload-dir: uploads/

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    root: INFO
    com.semenova.cloudstorage: DEBUG